### ISSUE TITLE
Not able to onboard a fresh install since 8.x tmos upgrade to 15.1.0.1 due to password-policy requirements

### ISSUE THREAD

**Issue by tthomas0702** [f5devcentral/ansible-role-bigiq_onboard#10]
Since 8.x I have not been able to run onboard_bigiq on a BIG-IQ that while the BIG-IQ is in a first boot state or after "clear-rest-storage -d" because I run up against the password-policy requirements to:

1) login with the default root password
2) create a new default root password

The readme does not mention any steps required to prepare the BIG-IQ for onboarding, so I am assuming that this role has a method to onboard a BIG-IQ in its default first-time boot-up state. 

But I cannot get it to work. The SSH connection fails. 

Questions: 
* Should I be able to onboard a fresh first-time boot BIG-IQ?
* Are there any required steps to prepare the BIG-IQ not stated in the readme?

Here is an example run. I am using almost all defaults from the vars/main.yml
* only change to the main.yml is added: "ansible_user:  root"

tthomas@sinkhole3:~/f5gitlab/ob_bigiq-8.x-test$ ansible-playbook  -vvv playbooks/onboard.yaml -i inventory/160.yaml
ansible-playbook 2.10.9
  config file = None
  configured module search path = ['/home/tthomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/share/pipx/venvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
No config file found; using defaults
host_list declined parsing /home/tthomas/f5gitlab/ob_bigiq-8.x-test/inventory/160.yaml as it did not pass its verify_file() method
script declined parsing /home/tthomas/f5gitlab/ob_bigiq-8.x-test/inventory/160.yaml as it did not pass its verify_file() method
Parsed /home/tthomas/f5gitlab/ob_bigiq-8.x-test/inventory/160.yaml inventory source with yaml plugin
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: onboard.yaml ***************************************************************************************************************************************************************************
1 plays in playbooks/onboard.yaml
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'

PLAY [Set up a CM BIG-IQ] ************************************************************************************************************************************************************************
Read vars_file '/home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml'

TASK [Gathering Facts] ***************************************************************************************************************************************************************************
task path: /home/tthomas/f5gitlab/ob_bigiq-8.x-test/playbooks/onboard.yaml:1
<10.3.214.160> ESTABLISH SSH CONNECTION FOR USER: root
<10.3.214.160> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/tthomas/.ansible/cp/31654e90fd 10.3.214.160 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<10.3.214.160> (1, b'', b'WARNING: Your password has expired.\nPassword change required but no TTY available.\n')
<10.3.214.160> Failed to connect to the host via ssh: WARNING: Your password has expired.
Password change required but no TTY available.
<10.3.214.160> ESTABLISH SSH CONNECTION FOR USER: root
<10.3.214.160> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/tthomas/.ansible/cp/31654e90fd 10.3.214.160 '/bin/sh -c '"'"'echo "`pwd`" && sleep 0'"'"''
<10.3.214.160> (1, b'', b'WARNING: Your password has expired.\nPassword change required but no TTY available.\n')
<10.3.214.160> Failed to connect to the host via ssh: WARNING: Your password has expired.
Password change required but no TTY available.
<10.3.214.160> ESTABLISH SSH CONNECTION FOR USER: root
<10.3.214.160> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/tthomas/.ansible/cp/31654e90fd 10.3.214.160 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp `"&& mkdir "` echo ~/.ansible/tmp/ansible-tmp-1627411378.383814-59049-247068104190063 `" && echo ansible-tmp-1627411378.383814-59049-247068104190063="` echo ~/.ansible/tmp/ansible-tmp-1627411378.383814-59049-247068104190063 `" ) && sleep 0'"'"''
<10.3.214.160> (1, b'', b'WARNING: Your password has expired.\nPassword change required but no TTY available.\n')
<10.3.214.160> Failed to connect to the host via ssh: WARNING: Your password has expired.
Password change required but no TTY available.
fatal: [10.3.214.160]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp `\"&& mkdir \"` echo ~/.ansible/tmp/ansible-tmp-1627411378.383814-59049-247068104190063 `\" && echo ansible-tmp-1627411378.383814-59049-247068104190063=\"` echo ~/.ansible/tmp/ansible-tmp-1627411378.383814-59049-247068104190063 `\" ), exited with result 1",
    "unreachable": true
}

PLAY RECAP ***************************************************************************************************************************************************************************************
10.3.214.160               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by rjouhann** [comment]
Hello @tthomas0702,

The role detects the version and should reset the expired password using bigiq_onboard_new_admin_password and bigiq_onboard_old_admin_password.

Could you check if both variables are correctly set and eventually share playbooks/onboard.yaml and inventory/160.yaml? 

**tasks/main.yaml**

```
# Due to TMOS change in 8.0, need to set new admin password which is expired by default
- name: Reset expired password starting BIG-IQ 8.0
  include_tasks: setup-reset-expired-password8_0.yaml
  when:
    - authtokenonb.json.expired is defined
    - authtokenonb.json.expired|bool
    - system_status.json.build is defined
    - system_status.json.build is not match("^\D+.[7-].[0-].*$") and
      system_status.json.build is not match("^\D+.[6-].[0-1].*$") and
      system_status.json.build is not match("^\D+.[7-].[1-].*$")
```

**tasks/setup-reset-expired-password8_0.yaml**

```
- name: Set new admin password
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/reset-expired-password"
    method: POST
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    body:
      username: "admin"
      currentPassword: "{{ bigiq_onboard_old_admin_password }}"
      newPassword: "{{ bigiq_onboard_new_admin_password }}"
    body_format: json

- name: Get authentication token using new admin password
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/authn/login"
    method: POST
    timeout: "{{ bigiq_onboard_timeout }}"
    validate_certs: "{{ bigiq_onboard_validate_certs }}"
    body:
      username: "admin"
      password: "{{ bigiq_onboard_new_admin_password }}"
    body_format: json
  register: authtokenonb
```

Thanks & Regards,
Roman

**Comment by tthomas0702** [comment]
I have left bigiq_onboard_new_root_password and  bigiq_onboard_new_admin_password empty because to this line in the readme:

"Parameters used to change the default admin and root accounts on the BIG-IQ during onboarding. If you do not want to change the passwords, leave the new variables empty."

### Here is the main.yaml 


```
---

ansible_user:  root   # added by Tim
bigiq_onboard_server: "{{ ansible_host }}"
bigiq_onboard_server_port: 443
bigiq_onboard_user: admin
bigiq_onboard_password: admin
bigiq_onboard_validate_certs: false
bigiq_onboard_transport: rest
bigiq_onboard_timeout: 120

bigiq_onboard_new_root_password:
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password:
bigiq_onboard_old_admin_password: "{{ bigiq_onboard_password }}"
bigiq_onboard_node_type: cm
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
bigiq_onboard_dns_search:
  - localhost
bigiq_onboard_ntp_servers:
  - time.nist.gov
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key:
bigiq_onboard_hostname: "{{ inventory_hostname }}"
bigiq_onboard_force: false
bigiq_onboard_discovery_address: "{{ discoveryip | default(ansible_host) }}"
bigiq_onboard_set_basic_auth: false
```


## Here is the playbook playbooks/onboard.yaml
```
- name: Set up a CM BIG-IQ
  hosts: bigiqs
  vars_files:
    - /home/tthomas/f5gitlab/ob_bigiq-8.x-test/vars/main.yaml
  roles:
    - { role: f5devcentral.bigiq_onboard }
```


## I changed the connection section to this and get the same failure:


```
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: "{{ bigiq_onboard_password }}"
```
